name: pica_crawler

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: default
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: main logic
        run: |
          python a.py
          git add test1.txt
