name: pica_crawler

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: main logic
        run: |
          git add downloads.txt
          git checkout main
          git add downloads.txt
      # push代码保留本次的下载结果
      - name: commit & push
        uses: actions-go/push@master
        with:
          # 提交代码时配置的git邮箱
          author-email: 'qifengatru@163.com'
          # 提交代码时配置的提交人姓名
          author-name: 'GitHub Actions'
          commit-message: 'update downloaded comics'
          token: ${{ secrets.GIT_TOKEN }}
