name: pica_crawler

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          pip install urllib3
          pip install requests
      - name: main logic
        run: |
          git add download.txt
          git checkout main
          git add download.txt
      # push代码保留本次的下载结果
      - name: commit & push
        uses: actions-go/push@master
        with:
          # 提交代码时配置的git邮箱
          author-email: 'qifengatru@163.com'
          # 提交代码时配置的提交人姓名
          author-name: 'GitHub Actions'
          commit-message: 'update downloaded comics'
          token: ${{ secrets.GIT_TOKEN }}
